### ISSUE TITLE
Broken settings page

### ISSUE THREAD

**Issue by cwarwicker** [gamoteca/moodle-mod_gamoteca#12]
The settings page of the plugin is currently broken with a 'section' error.

![image](https://user-images.githubusercontent.com/2445720/219667279-1f3bff25-0ed5-45d9-8b57-04a6c76260c4.png)

In addition, you are referencing the wrong plugin name in your settings. This currently won't break anything, but should be fixed.

A fix for this has been added in #11

**Comment by Tunyesz** [comment]
Thank you for letting us know about the issue with the settings page of our plugin. 

We appreciate that you took the time to provide a solution for the issue, and we are glad to inform you that it has been successfully merged.
