### ISSUE TITLE
invalid privacy api class

### ISSUE THREAD

**Issue by danmarsden** [gamoteca/moodle-mod_gamoteca#5]
It seems that a null provider class has been implemented which is incorrect - the gamoteca_data table includes user data so needs to be covered, but also as this plugin integrates with an external service I suspect user information may be passed to the external service so the external_links_location part of the api may also need to be implemented.

note this is a blocker for plugins db approval as this plugin integrates with an external service. More information on the privacy api is here:
https://moodledev.io/docs/apis/subsystems/privacy/

**Comment by Tunyesz** [comment]
Updated with database and lti privacy info  #9

**Comment by danmarsden** [comment]
thanks... looks like you're making a some progress there! :-)

but... the gamoteca table doesn't need to be included in the get_metadata table:
$collection->add_database_table('gamoteca',) 

because it doesn't store any user data - just the configuration information about the activity.

Where-as the "gamoteca_data" does include user data (shown by the fact it has a userid field) and stores information about scores/timesspent for that user - so that part looks good.

Then... you're missing the api functions required to export/delete the data in the gamoteca_data table from the privacy api class:
https://moodledev.io/docs/apis/subsystems/privacy/#providing-a-way-to-export-user-data
https://moodledev.io/docs/apis/subsystems/privacy/#providing-a-way-to-delete-user-data

It's possible we'd approve the plugin in the plugins db without the export/delete api functions, as the bare-minimum components are included,  but some organisations will not be able to use your plugin as it will fail continuous integration process/automated tests which many organisations use as part of  their deployment processes.

**Comment by Tunyesz** [comment]
Updated with empty export/delete functions in  #10. We plan to implement these functions in a later/next iteration.
