### ISSUE TITLE
function naming violations

### ISSUE THREAD

**Issue by danmarsden** [gamoteca/moodle-mod_gamoteca#8]
https://github.com/gamoteca/gamoteca-moodle-lti-plugin/blob/master/lib.php#L179-L197

functions like "encrypt" or "unparse_url" are invalid.
all functions in your plugin must be prefixed with the frankenstyle plugin name "mod_gamoteca" or in the case of activity module plugins the "mod_" part can be excluded. Alternatively they can be in namespaced classes.

more info on this is here:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle

note this is a blocker for plugins db approval.

**Comment by Tunyesz** [comment]
Updated the function names in  #9
